export const projects = [
  {
    id: "uvu-bookstore",
    title: "UVU Bookstore Redesign",
    blurb:
      "End-to-end UX case study: stakeholder collaboration, research synthesis, wireframes, high-fidelity Figma prototypes, and usability-informed homepage improvements.",
    tags: ["UX Research", "UI Design", "Figma", "Usability Testing", "Responsive"],
    href: "case-studies/uvu-bookstore.html",
    image: "assets/img/bookstore-hero.webp",
    heroImage: "assets/img/uvu-bookstore-homepage-mockup.webp",
    featured: true,
    spotlight: true,
  },
  {
    id: "coded-diner",
    title: "Coded Diner Website",
    blurb: "Responsive website built with HTML and CSS—translating layout decisions into clean, accessible code.",
    tags: ["HTML", "CSS", "Responsive", "UI Design"],
    href: "case-studies/diner.html",
    image: "assets/img/velombra-mockup.webp",
    heroImage: "assets/img/velombra-mockup.webp",
    featured: true,
  },
  {
    id: "sweatshop",
    title: "Sweatshop Interactive Website",
    blurb: "Immersive storytelling experience designed and prototyped in Framer with a focus on interaction and narrative flow.",
    tags: ["UX", "Interaction Design", "Framer"],
    href: "case-studies/sweatshop.html",
    image: "assets/img/sweatshops-homecard.webp",
    heroImage: "assets/img/sweatshop-mockup.webp",
    featured: true,
  },
  {
    id: "multimedia",
    title: "Multimedia Optimization Research",
    blurb: "UX research exploring media formats, performance trade-offs, and user experience implications.",
    tags: ["UX Research", "Usability", "Performance"],
    href: "case-studies/multimedia.html",
    image: "assets/img/multimedia-homecard.webp",
    heroImage: "assets/img/multimedia-mockup.webp",
  },
  {
    id: "disney-motion",
    title: "Disney Castle Motion Graphic",
    blurb: "Motion graphic created in After Effects exploring lighting, atmosphere, and cinematic timing.",
    tags: ["After Effects", "Motion Design", "Animation"],
    href: "case-studies/disney-motion.html",
    image: "assets/img/Disneyfirework1.webp",
    heroImage: "assets/img/disney-castle-cover.webp",
  },
  {
    id: "remarried-graphic",
    title: "Survival Guide for Getting Remarried",
    blurb: "Editorial booklet design focused on typography, layout hierarchy, and print-ready production.",
    tags: ["InDesign", "Graphic Design", "Typography"],
    href: "case-studies/booklet-graphic.html",
    image: "assets/img/remarriedgraphicdesign.webp",
    heroImage: "assets/img/remarriedgraphicdesign.webp",
  },
];

export const heroProjects = projects.filter((project) => project.featured);
